### PR TITLE
[LTS] fix groups create

### PR DESCRIPTION
**Pull request by vladimirvshivkov**
Acceptance test passed:
```
=== RUN   TestLtsGroupsLifecycle
2022/09/05 14:54:19 Creating LTS Group, ID: 7868a4e0-9b1b-4a4e-a77b-4d63b85314ec
--- PASS: TestLtsGroupsLifecycle (1.46s)
PASS
```

### CODE REVIEW

**Review by Aloento — DISMISSED** [review]

**Review by Aloento — DISMISSED** [review]

**Review by Aloento — DISMISSED** [review]

**Comment by vladimirvshivkov** [comment]
recheck

**Comment by anton-sidelnikov** [comment]
tests?

**Comment by vladimirvshivkov** [comment]
> tests?

added

**Review by anton-sidelnikov — APPROVED** [review]

**Review by Aloento — APPROVED** [review]

**Comment by Aloento** [comment]
```
TASK [ensure-golangci-lint : Install golangci-lint]
Failure downloading https://github.com/golangci/golangci-lint/releases/download/v1.45.2/golangci-lint-1.45.2-linux-amd64.tar.gz, Connection failure: The read operation timed out
```

?

**Comment by Aloento** [comment]
regate

**Pull request merged**
