### PR TITLE
Auth: implementation of temp AK/SK auth

### PR DESCRIPTION
**Pull request by artem-lifshits**
### What this PR does / why we need it
PR implements provider authorization by using temporary AK/SK and security key.

### CODE REVIEW

**Review by anton-sidelnikov — DISMISSED** [review]

**Review by Polina-Gubina — DISMISSED** [review]

**Comment by artem-lifshits** [comment]
Regate

**Comment by artem-lifshits** [comment]
Regate

**Comment by artem-lifshits** [comment]
Regate

**Comment by artem-lifshits** [comment]
Regate

**Review by Aloento — DISMISSED** [review]

**Comment by artem-lifshits** [comment]
Recheck

**Review by Polina-Gubina — APPROVED** [review]

**Review by anton-sidelnikov — APPROVED** [review]

**Comment by artem-lifshits** [comment]
Regate

**Review by Aloento — APPROVED** [review]

**Pull request merged**
