### PR TITLE
[DMS] Remove DMS queues and groups

### LINKED ISSUE #392: DMS queues and groups Deprecated and Removed
```json
{
	"request_id": "",
	"error_code": "APIGW.0201",
	"error_msg": "Service DMS is currently unavailable"
}
```

### PR DESCRIPTION
**Pull request by Aloento**
### What this PR does / why we need it

Remove DMS queues and groups

### Which issue this PR fixes

fixes #392

### CODE REVIEW

**Review by outcatcher — CHANGES_REQUESTED** [review]
`clients.NewDmsV1Client()` should also be removed

**Comment by lego963** [comment]
> `clients.NewDmsV1Client()` should also be removed

not all dms apis are deleted

**Comment by outcatcher** [comment]
> my bad, did you mean client in `acceptance`?

Yes, acceptance client.

**Comment by lego963** [comment]
> > my bad, did you mean client in `acceptance`?
> 
> Yes, acceptance client.

we can use it in another pkgs, we need to have it (like dms product)

**Comment by Aloento** [comment]
NewDmsV1Client still in used

**Comment by outcatcher** [comment]
Haven't noticed it in instances tests, sorry

**Review by outcatcher — APPROVED** [review]

**Review by lego963 — APPROVED** [review]

**Comment by outcatcher** [comment]
regate

**Pull request merged**
