### PR TITLE
[DDS]: Refactoring and new features

### LINKED ISSUE #484: [DDS] add endpoint for enlarging dds volumes
https://docs.otc.t-systems.com/en-us/api/dds/dds_api_0024.html

### PR DESCRIPTION
**Pull request by artem-lifshits**
### Which issue this PR fixes
DDS refactoring and new features.
Logs and backups functionality not included.

### CODE REVIEW

**Comment by artem-lifshits** [comment]
=== RUN   TestDdsLifeCycle
    instances_test.go:154: Attempting to create DDSv3 replica set instance
    instances_test.go:201: DDSv3 replica set instance successfully created: 5fd716c68a9245d8add23740800587dain02
    tools.go:72: {
          "id": "5fd716c68a9245d8add23740800587dain02",
          "name": "dds-acc-ei46jFqd",
          "datastore": {
            "type": "DDS-Community",
            "version": "4.0",
            "storage_engine": "wiredTiger"
          },
          "created": "2022-12-29 17:33:49",
          "status": "creating",
          "region": "eu-de",
          "availability_zone": "eu-de-01",
          "vpc_id": "3166da85-07c3-4113-8a21-b9975458a1af",
          "subnet_id": "7aa19a7c-d0ea-4e02-a06b-30cfe2c8fe1f",
          "security_group_id": "738517ba-a383-4653-a5c9-4d225ee5736e",
          "disk_encryption_id": "",
          "mode": "Single",
          "flavor": [
            {
              "type": "single",
              "num": "1",
              "size": "20",
              "spec_code": "dds.mongodb.s2.medium.4.single"
            }
          ],
          "backup_strategy": {
            "start_time": "08:15-09:15",
            "keep_days": "7"
          },
          "ssl_option": "0",
          "job_id": "740b0265-d630-4d19-9b11-c85756caffe3"
        }
    tools.go:72: {
          "id": "5fd716c68a9245d8add23740800587dain02",
          "name": "dds-acc-ei46jFqd",
          "status": "normal",
          "port": "8635",
          "mode": "Single",
          "region": "eu-de",
          "datastore": {
            "type": "DDS-Community",
            "version": "4.0",
            "storage_engine": ""
          },
          "engine": "wiredTiger",
          "created": "2022-12-29T17:38:27",
          "updated": "2022-12-29T17:38:26",
          "db_user_name": "rwuser",
          "ssl": 0,
          "vpc_id": "3166da85-07c3-4113-8a21-b9975458a1af",
          "subnet_id": "7aa19a7c-d0ea-4e02-a06b-30cfe2c8fe1f",
          "security_group_id": "738517ba-a383-4653-a5c9-4d225ee5736e",
          "backup_strategy": {
            "start_time": "08:00-09:00",
            "keep_days": 7
          },
          "maintenance_window": "14:00-18:00",
          "groups": [
            {
              "type": "single",
              "id": "",
              "name": "",
              "status": "",
              "volume": {
                "size": "20",
                "used": "0.3364448547363281"
              },
              "nodes": [
                {
                  "id": "5e5a893ee19f4aa79ec81426e17d5783no02",
                  "name": "dds-acc-ei46jFqd_single_node_1",
                  "status": "normal",
                  "role": "Primary",
                  "private_ip": "192.168.1.45",
                  "public_ip": "",
                  "spec_code": "dds.mongodb.s2.medium.4.single",
                  "availability_zone": "eu-de-01"
                }
              ]
            }
          ],
          "disk_encryption_id": "",
          "time_zone": "",
          "actions": [],
          "pay_mode": "0"
        }
    instances_test.go:50: Update name
    helpers.go:59: Attempting to create eip/bandwidth
    helpers.go:75: Waiting for eip 6e4d06a2-5d5e-447f-9096-3444a19e227d to be active
    helpers.go:82: Created eip/bandwidth: 6e4d06a2-5d5e-447f-9096-3444a19e227d
    instances_test.go:67: AttachEip
    instances_test.go:79: UnbindEip
    instances_test.go:89: Enable the SSL
    instances_test.go:95: Enable config IP
    instances_test.go:103: Modify instance internal IP
    instances_test.go:112: Modify instance port
    instances_test.go:120: Modify instance SG
    instances_test.go:128: Modify instance specs
    instances_test.go:143: Modify instance volume size
    instances_test.go:258: Attempting to delete DDSv3 instance: 5fd716c68a9245d8add23740800587dain02
    instances_test.go:268: DDSv3 instance deleted successfully: 5fd716c68a9245d8add23740800587dain02
    helpers.go:88: Attempting to delete eip/bandwidth: 6e4d06a2-5d5e-447f-9096-3444a19e227d
    helpers.go:94: Waitting for eip 6e4d06a2-5d5e-447f-9096-3444a19e227d to be deleted
    helpers.go:99: Deleted eip/bandwidth: 6e4d06a2-5d5e-447f-9096-3444a19e227d
--- PASS: TestDdsLifeCycle (801.92s)
PASS

Process finished with the exit code 0

**Comment by Aloento** [comment]
Let me add field doc

**Review by Aloento — CHANGES_REQUESTED** [review]
Let me add field doc

**Review by Aloento — APPROVED** [review]
Since this is an urgent PR, I suspended work.

**Review by anton-sidelnikov — APPROVED** [review]

**Pull request merged**
