### PR TITLE
[Refactor] CBR

### PR DESCRIPTION
**Pull request by Aloento**
Move all API methods and related structures to a separate file.
Inline all `Extracts` and use the `extract` package instead.
Remove all Builders

### CODE REVIEW

**Review by outcatcher — DISMISSED** [review]

**Comment by Aloento** [comment]
4 FAIL in `cbr/v3/vaults_test.go` : `unsupported type: func() (io.ReadCloser, error)`

Seems like IntoStructPtr and IntoSlicePtr not support `io.ReadCloser`
Maybe we can waiting https://github.com/opentelekomcloud/gophertelekomcloud/pull/416

**Comment by Aloento** [comment]
repost

**Comment by Aloento** [comment]
repost

**Comment by outcatcher** [comment]
> 4 FAIL in `cbr/v3/vaults_test.go` : `unsupported type: func() (io.ReadCloser, error)`
> 
> 
> 
> Seems like IntoStructPtr and IntoSlicePtr not support `io.ReadCloser`
> 
> Maybe we can waiting https://github.com/opentelekomcloud/gophertelekomcloud/pull/416

Unsupported type is not ` io.ReadCloser`, but a `func() (io.ReadCloser, error)`, function type.

**Review by outcatcher — DISMISSED** [review]

**Comment by Aloento** [comment]
funny, one approve can trigger `post`.

**Review by anton-sidelnikov — APPROVED** [review]

**Review by artem-lifshits — APPROVED** [review]

**Pull request merged**
