### PR TITLE
EIP tags implementation

### PR DESCRIPTION
**Pull request by lego963**
Implement VPCv1 elastic IP tagging

```
=== RUN   TestEipsTagsList
--- PASS: TestEipsTagsList (5.60s)
=== RUN   TestEipsTagsLifecycle
--- PASS: TestEipsTagsLifecycle (10.99s)
PASS

Process finished with exit code 0
```

### CODE REVIEW

**Comment by outcatcher** [comment]
recheck

**Review by outcatcher — DISMISSED** [review]

**Comment by lego963** [comment]
recheck

**Review by anton-sidelnikov — DISMISSED** [review]

**Review by outcatcher — DISMISSED** [review]

**Review by anton-sidelnikov — DISMISSED** [review]

**Review by outcatcher — DISMISSED** [review]

**Review by outcatcher — DISMISSED** [review]

**Comment by lego963** [comment]
recheck

**Review by anton-sidelnikov — APPROVED** [review]

**Review by outcatcher — APPROVED** [review]

**Comment by lego963** [comment]
recheck

**Comment by lego963** [comment]
regate

**Pull request merged**
